# Generated by Django 6.0 on 2026-08-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
